# Generated by Django 5.1 on 2024-08-31 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('X', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xtweet',
            name='photo',
            field=models.ImageField(upload_to='photos/'),
        ),
    ]
