# Generated by Django 5.1 on 2024-09-06 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('X', '0002_alter_xtweet_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xtweet',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='xtweet',
            name='text',
            field=models.TextField(),
        ),
    ]
